### ISSUE TITLE
Impossible to push to the repository

### ISSUE THREAD

**Issue by gabriel-logan** [ariyoaresa/ai-list#4]
You stated that you want contributors, but block the person from making a contribution?

![image](https://github.com/ariyoaresa/ai-list/assets/96627244/d0bb64bf-184c-4b24-8f24-bb33b5ee7969)

**Comment by ariyoaresa** [comment]
I'm very sorry about that, how about you fork the repo, create a new branch, make the changes right here on GitHub and make a pull request

**Comment by ariyoaresa** [comment]
> You stated that you want contributors, but block the person from making a contribution?
> 
> ![image](https://private-user-images.githubusercontent.com/96627244/317664768-d0bb64bf-184c-4b24-8f24-bb33b5ee7969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjU5NTcsIm5iZiI6MTcxMTYyNTY1NywicGF0aCI6Ii85NjYyNzI0NC8zMTc2NjQ3NjgtZDBiYjY0YmYtMTg0Yy00YjI0LThmMjQtYmIzM2I1ZWU3OTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDExMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YThhOGNhZTg5ZDI5ZmVlMGNmYjA5MGYzMDZhNTkxYWM2ZWQxZjk0MDYxMWEzMzdmOWI0YzAzYjRjOGFiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7E5W_UvcxxIw5LqdVxWj20YdjzyW3eSPZOXBriPKzE)

Are you sure you forked the repo first?

**Comment by LyubomirT** [comment]
@gabriel-logan You need write access for the repo, and that's what only Collaborators (Collaborators != Contributors) have. Please fork the repo, then add your changes -> push to your clone -> go to this repo -> create a Pull Request with your changes.
